EcoHouse/Controllers/Another_AddressController.cs
using EcoHouse.Logic.Another_Address;
using EcoHouse.Models;
using EcoHouse.Storage.Entities;
using Microsoft.AspNetCore.Mvc;


namespace EcoHouse.Controllers;

public class Another_AddressController : Controller
{
    private readonly IAnother_AdressManager _manager;

    public Another_AddressController (IAnother_AdressManager manager)
    {
        _manager = manager;
    }

    public async Task<IActionResult> Order()
    {
        var address = await _manager.GetAll();

        return View(address);
    }

    [HttpGet]
    [Route("another_addresses")]
    public async Task<IList<Another_Adresses>> GetAll() => await _manager.GetAll();

    //[HttpPut]
    //[Route("another_addresses")]
    //public Task Create([FromBody] CreateAnother_AddressRequest request) => _manager.Create(request.Area, request.Street, request.Number_Of_House, request.Number_Of_Apartment);
    [HttpPost]
    public IActionResult CreateAddres(string Area, string Street, int Number_Of_House, int Number_Of_Apartment)
    {
        _manager.Create(Area, Street, Number_Of_House, Number_Of_Apartment);
        return RedirectToAction(nameof(Order));
    }
   
    [HttpDelete]
    [Route("another_addresses/{Id}")]
    public Task Delete(int id) => _manager.Delete(id);

}

EcoHouse/Views/Another_Address/Main.cshtml
@model IList<EcoHouse.Storage.Entities.Another_Adresses>

    <h1>Адреса:</h1>
    <table>
        <tr>
            <th>
                Идентификатор адреса
            </th>
            <th>
                Город
            </th>
            <th>
                Улица
            </th>
            <th>
                Дом
            </th>
            <th>
                Квартира
            </th>
        </tr>
    @foreach(var address in Model)
    {
        <tr>
            <td>@address.Address_ID</td>
            <td>@address.Area</td>
            <td>@address.Street</td>
            <td>@address.Number_Of_House</td>
            <td>@address.Number_Of_Apartment</td>
        </tr>
    }
</table>

<div>
<h1>Create addres</h1>
@using (Html.BeginForm("CreateAddres", "Another_Address", FormMethod.Post))
{
<textarea name = "Area"></textarea>
<textarea name = "Street"></textarea>
<textarea name = "Number_Of_House"></textarea>
<textarea name = "Number_Of_Apartment"></textarea>

<button type = "submit">Create</button>
}
</div>