EcoHouse/Controllers/DishController.cs
using EcoHouse.Logic.Dishes;
using EcoHouse.Models;
using EcoHouse.Storage.Entities;
using Microsoft.AspNetCore.Mvc;
using Korzh.EasyQuery.Linq;
using EcoHouse.Storage;
using EcoHouse.Logic.Structures;
using EcoHouse.Logic.Orders;
using EcoHouse.Logic.Users;
using EcoHouse.Logic.Products;
using EcoHouse.Logic.Categories;

namespace EcoHouse.Controllers;
public class DishController : Controller
{
    private readonly IDishManager _managerDish;
    private readonly IStructureManager _managerStructure;
    private readonly IProductManager _managerProduct;
    private readonly ICategoryManager _managerCategory;
    private static IOrderManager _managerOrder;
    static private int _dishID = -1;
    static private int _productID = -1;
    static private int _categoryID = -1;
    public DishController(IDishManager managerDish, IStructureManager managerStructure, IOrderManager managerOrder, IProductManager managerProduct, ICategoryManager managerCategory)
    {
        _managerDish = managerDish;
        _managerStructure = managerStructure;
        _managerOrder = managerOrder;
        _managerProduct = managerProduct;
        _managerCategory = managerCategory;
    }
    public async Task<IActionResult> Menu()
    {
        _dishID = -1;
        ViewBag.Dishes = await _managerDish.GetAll();
        ViewBag.Structures = await _managerStructure.GetAll();
        ViewBag.Orders = await _managerOrder.GetAll();
        ViewBag.User = UsersController.CurrentUser;
        return View();
    }
    public async Task<IActionResult> MenuChoice()
    {
        if (_productID == -1)
        {
            return Redirect("~/Home/Index");
        } else
        {
            _dishID = -1;
            ViewBag.Dishes = await _managerDish.GetAll();
            ViewBag.Structures = await _managerStructure.GetAll();
            ViewBag.Orders = await _managerOrder.GetAll();
            ViewBag.ProductID = _productID;
            ViewBag.Products = await _managerProduct.GetAll();
            ViewBag.User = UsersController.CurrentUser;
            return View();
        }
    }
    public async Task<IActionResult> MenuCategory()
    {
        if (_categoryID == -1)
        {
            return Redirect("~/Home/Index");
        }
        else
        {
            _dishID = -1;
            ViewBag.Dishes = await _managerDish.GetAll();
            ViewBag.Structures = await _managerStructure.GetAll();
            ViewBag.Orders = await _managerOrder.GetAll();
            ViewBag.CategoryID = _categoryID;
            ViewBag.Category = await _managerCategory.GetAll();
            ViewBag.User = UsersController.CurrentUser;
            return View();
        }
    }
    public async Task<IActionResult> Dish()
    {
        ViewBag.Dishes = await _managerDish.GetAll();
        ViewBag.Structures = await _managerStructure.GetAll();
        ViewBag.Orders = await _managerOrder.GetAll();
        ViewBag.SaveDish = _dishID;
        ViewBag.User = UsersController.CurrentUser;
        if (ViewBag.SaveDish == -1)
        {
            return RedirectToAction("Menu");
        }
        else
        {
            return View();
        }
    }
    public async Task<IActionResult> Delivery()
    {
        _dishID = -1;
        ViewBag.Dishes = await _managerDish.GetAll();
        ViewBag.Structures = await _managerStructure.GetAll();
        ViewBag.Orders = await _managerOrder.GetAll();
        ViewBag.User = UsersController.CurrentUser;
        return View();
    }
    public IActionResult SaveDish(int dish)
    {
        _dishID = dish;
        return RedirectToAction("Dish");
    }
    public IActionResult SaveProduct(int product)
    {
        _productID = product;
        return RedirectToAction("MenuChoice");
    }
    public IActionResult SaveCategory(int category)
    {
        _categoryID = category;
        return RedirectToAction("MenuChoice");
    }

    [HttpGet]
    [Route("dishes")]
    public async Task<IList<Dish>> GetAll() => await _managerDish.GetAll();

    [HttpPut]
    [Route("dishes")]
    public Task Create([FromBody] CreateDishRequest request) => _managerDish.Create(request.Name, request.Structure_, request.Mass, request.Price, request.Description, request.CategoryID, request.Recipe, request.Link, request.ProductID);

    [HttpPost]
    public async Task<IActionResult> Menu(string Text)
    {
        var dishes = await _managerDish.GetAll();
        var dish = from m in dishes
                   select m;

        if (!string.IsNullOrEmpty(Text))
        {
            dish = dish.Where(s => s.Name.ToLower().Contains(Text.ToLower()));
        }
        ViewBag.Dishes = dish;
        ViewBag.Structures = await _managerStructure.GetAll();
        ViewBag.Orders = await _managerOrder.GetAll();
        return View();
    }

    [HttpDelete]

    [Route("dishes/{id}")]
    public Task Delete(int id) => _managerDish.Delete(id);

    #region Bucket
    public async Task<IActionResult> Add(int id, int price)
    {
        if (UsersController.CurrentUser != null)
        {
            var arr = await _managerOrder.GetAll();
            int orderId = arr[0].OrdersID;
            await _managerOrder.CostUp(price);
            await _managerDish.Add(id, orderId);
            return Redirect("~/Home/Basket");
        }
        else
        {
            return Redirect("~/Users/SignIn");
        }
    }

    public async Task<IActionResult> AntiAdd(int id, int price)
    {
        await _managerOrder.CostDown(price);
        await _managerDish.AntiAdd(id);
        return Redirect("~/Home/Basket");
    }

    #endregion
}

EcoHouse/Controllers/EcoHouseController.cs
using EcoHouse.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EcoHouse.Controllers
{
    public class EcoHouseController : Controller
    {
        private readonly ILogger<EcoHouseController> _logger;

        public EcoHouseController(ILogger<EcoHouseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Basket()
        {
            return View();
        }
        public IActionResult Delivery()
        {
            return View();
        }
        public IActionResult Dish()
        {
            return View();
        }
        public IActionResult Favorite()
        {
            return View();
        }
        public IActionResult Menu()
        {
            return View();
        }
        public IActionResult MenuChoice()
        {
            return View();
        }
        public IActionResult Order()
        {
            return View();
        }
        public IActionResult Personal()
        {
            return View();
        }
        public IActionResult SignIn()
        {
            return View();
        }
        public IActionResult SignUp()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EcoHouse/Controllers/OrderController.cs
using EcoHouse.Logic.Orders;
using EcoHouse.Models;
using EcoHouse.Storage.Entities;
using Microsoft.AspNetCore.Mvc;

namespace EcoHouse.Controllers;

public class OrderController : Controller
{
    private readonly IOrderManager _manager;

    public OrderController(IOrderManager manager)
    {
        _manager = manager;
    }
    [HttpGet]
    [Route("order")]
    public async Task<IList<Order>> GetAll() => await _manager.GetAll();

    [HttpPut]
    [Route("order")]
    public Task Create([FromBody] CreateOrderRequest request) => _manager.Create();




    [HttpDelete]
    [Route("order/{id}")]
    public Task Delete(int id) => _manager.Delete(id); 
}

EcoHouse/Views/EcoHouse/Basket.cshtml
@{
    ViewData["Title"] = "Корзина";
}

         <section class="basket start block">
            <div class="basket__container container">
               <h2 class="basket__title title">Корзина</h2>
               <div class="basket__content content-basket">
                  <div class="content-basket__table table-basket">
                     <div class="table-basket__head head-table">
                        <div class="head-table__product">Товар</div>
                        <div class="head-table__count">Количество</div>
                        <div class="head-table__price">Цена</div>
                        <div class="head-table__info">Информация</div>
                     </div>
                @for (var index = 1; index < 6; index++)
                {
                     <div class="table-basket__item item-table">
                        <div class="item-table__image">
                           <picture><source srcset="/img/dish/food3.webp" type="image/webp"><img src="/img/dish/food3.png" alt="food"></picture>
                        </div>
                        <div class="item-table__name">Салат с брокколи и цветной капусты</div>
                        <div class="item-table__count count-item control-count">
                           <button class="count-item__button sub">−</button>
                           <div class="count-item__value count">1</div>
                           <button class="count-item__button inc">+</button>
                        </div>
                        <div class="item-table__price">250 ₽</div>
                        <div class="item-table__control control-item">
                           <button class="control-item__remove remove-button">Удалить</button>
                        </div>
                     </div>
                }
                  </div>
                  <div class="content-basket__registration registration-basket">
                     <div class="registration-basket__head">Оформление</div>
                     <div class="registration-basket__content registration-content-basket">
                        <div class="registration-content-basket__all all-registration-content">
                           <div class="all-registration-content__name">Всего <span class="count">(3)</span></div>
                           <div class="all-registration-content__count registration-price">1069 ₽</div>
                        </div>
                        <div class="all-registration-content__sale all-registration-content">
                           <div class="all-registration-content__name registration-sale">Скидка <span
                                 class="sale">-0%</span></div>
                           <div class="all-registration-content__count">0 ₽</div>
                        </div>
                        <div class="registration-content-basket__promo promo-basket">
                           <form class="form promo-form">
                              <div class="promo-form__place">
                                 <input class="promo" type="text" name="promo" placeholder="Промокод">
                                 <button class="input-yes icon-yes" type="submit" value="" name="submit"></button>
                              </div>
                              <div class="form__error-promo">Промокод неправильный</div>
                              <div class="form__error-promo-well">Промокод применен</div>
                           </form>
                        </div>
                        <div class="all-registration-content__sale all-registration-content">
                           <div class="all-registration-content__name">Стоимость</div>
                           <div class="all-registration-content__count all-price">1069 ₽</div>
                        </div>
                        <a asp-area="" asp-controller="EcoHouse" asp-action="Order" class="content-enter__sign">Оформить</a>
                     </div>
                  </div>
               </div>
            </div>
         </section>

EcoHouse/Views/EcoHouse/Favorite.cshtml
@{
    ViewData["Title"] = "Продукт";
}

         <section class="favorite start block margin">
            <div class="favorite__container container">
               <h2 class="favorite__title title">Выберите любимый продукт, а мы подберём блюдо</h2>
               <div class="favorite__search">
                  <form class="search__form form">
                     <input class="search-input" type="text" name="search" placeholder="Введите продукт">
                     <ul class="search-input__list">
            @for (var index = 1; index < 9; index++) 
            {
                        <li><a asp-area="" asp-controller="EcoHouse" asp-action="Dish">Брокколи</a></li>
            }
                     </ul>
                  </form>
               </div>
               <div class="favorite__content content-choice">
            @for (var index = 1; index < 29; index++) 
            {
                  <a asp-area="" asp-controller="EcoHouse" asp-action="Dish" class="content-choice__item item-choice">
                     <div class="item-choice__image">
                        <picture><source srcset="/img/content/broccoli.webp" type="image/webp"><img src="/img/content/broccoli.png" alt="image"></picture>
                     </div>
                     <div class="item-choice__text">Брокколи</div>
                  </a>
            }
               </div>
            </div>
         </section>

EcoHouse/Views/EcoHouse/Menu.cshtml
@{
    ViewData["Title"] = "Меню";
}

         <section class="menu start block margin">
            <div class="menu__container container">
               <div class="menu__head head-menu">
                  <h2 class="head-menu__title title">Наши блюда</h2>
               </div>
               <div class="menu__content content-menu">
            @for (var index = 1; index < 8; index++)
            {
                  <div class="content-menu__item item-menu">
                     <div class="item-menu__image">
                        <picture><source srcset="/img/dish/food3.webp" type="image/webp"><img src="/img/dish/food3.png" alt="food"></picture>
                     </div>
                     <div class="item-menu__about about-menu-item">
                        <h3 class="about-menu-item__title">Салат с брокколи и цветной капусты</h3>
                        <div class="about-menu-item__content content-item">
                           <div class="content-item__desc">Полезный и вкусный салат из брокколи и цветной капусты,
                              сваренных на пару, разнообразит завтрак и отлично дополнит обед или ужин.</div>
                           <div class="content-item__about about-content-item">
                              <h3 class="about-content-item__title">О блюде:</h3>
                              <div class="about-content-item__kcal">48 ккал/100 г</div>
                              <div class="about-content-item__menu">
                                 <picture><source srcset="/img/icons/menu.webp" type="image/webp"><img src="/img/icons/menu.png" alt="menu"></picture>
                                 <ul class="about-content-item__list">
                                        @for (var product = 1; product < 8; product++)
                                        {
                                        <li>Брокколи</li>
                                        }
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="about-menu-item__control control-item">
                           <a asp-area="" asp-controller="EcoHouse" asp-action="Dish" class="control-item__button button-default">Рецепт<span
                                 class="icon-fork"></span></a>
                           <a href="#" class="control-item__button buy button-default">
                              <picture><source srcset="/img/icons/scooter.webp" type="image/webp"><img src="/img/icons/scooter.png" alt="scooter"></picture>Заказать
                              <span class="icon-spoon"></span>
                           </a>
                        </div>
                     </div>
                  </div>
            }
               </div>
            </div>
         </section>

EcoHouse/Views/EcoHouse/MenuChoice.cshtml
@{
    ViewData["Title"] = "Меню";
}

         <section class="menu start block margin">
            <div class="menu__container container">
               <div class="menu__head head-menu">
                  <h2 class="head-menu__title title">Вы выбрали</h2>
                  <div class="content-choice__item item-choice">
                     <div class="item-choice__image">
                        <picture><source srcset="/img/content/curd.webp" type="image/webp"><img src="/img/content/curd.png" alt="image"></picture>
                     </div>
                     <div class="item-choice__text">Творог</div>
                  </div>
               </div>
               <div class="menu__content content-menu">
            @for (var index = 1; index < 8; index++)
            {
                  <div class="content-menu__item item-menu">
                     <div class="item-menu__image">
                        <picture><source srcset="/img/dish/food3.webp" type="image/webp"><img src="/img/dish/food3.png" alt="food"></picture>
                     </div>
                     <div class="item-menu__about about-menu-item">
                        <h3 class="about-menu-item__title">Салат с брокколи и цветной капусты</h3>
                        <div class="about-menu-item__content content-item">
                           <div class="content-item__desc">Полезный и вкусный салат из брокколи и цветной капусты,
                              сваренных на пару, разнообразит завтрак и отлично дополнит обед или ужин.</div>
                           <div class="content-item__about about-content-item">
                              <h3 class="about-content-item__title">О блюде:</h3>
                              <div class="about-content-item__kcal">48 ккал/100 г</div>
                              <div class="about-content-item__menu">
                                 <picture><source srcset="/img/icons/menu.webp" type="image/webp"><img src="/img/icons/menu.png" alt="menu"></picture>
                                 <ul class="about-content-item__list">
                                        @for (var product = 1; product < 8; product++)
                                        {
                                        <li>Брокколи</li>
                                        }
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="about-menu-item__control control-item">
                           <a asp-area="" asp-controller="EcoHouse" asp-action="Dish" class="control-item__button button-default">Рецепт<span
                                 class="icon-fork"></span></a>
                           <a href="#" class="control-item__button buy button-default">
                              <picture><source srcset="/img/icons/scooter.webp" type="image/webp"><img src="/img/icons/scooter.png" alt="scooter"></picture>Заказать
                              <span class="icon-spoon"></span>
                           </a>
                        </div>
                     </div>
                  </div>
            }
               </div>
            </div>
         </section>

EcoHouse/Views/EcoHouse/Personal.cshtml
@{
    ViewData["Title"] = "Личный кабинет";
}

         <section class="personal start block">
            <div class="personal__container container">
               <div class="personal__content content-personal">
                  <div class="content-personal__about about-personal">
                     <div class="about-personal__image">
                        <picture><img src="/img/user/user1.jpg" alt="user"></picture>
                     </div>
                     <div class="about-personal__update">
                        <a href="#popup-form-image" class="popup-link icon-update">Обновить фотографию</a>
                     </div>
                     <div class="about-personal__name">Дуэйн “Скала” Джонсон</div>
                  </div>
                  <div class="content-personal__info info-personal">
                     <div class="info-personal__name">Ваша почта</div>
                     <div class="info-personal__content place-email">yaskala@hollywood.com</div>
                     <div class="info-personal__button"><a class="popup-link" href="#popup-form-email">Изменить</a>
                     </div>
                     <div class="info-personal__name">Ваш телефон</div>
                     <div class="info-personal__content place-number">+7 (999) 563 85-48</div>
                     <div class="info-personal__button"><a class="popup-link" href="#popup-form-phone">Изменить</a>
                     </div>
                     <div class="info-personal__name">Ваш пароль</div>
                     <div class="info-personal__content place-pass">••••••••••••••••••••••</div>
                     <div class="info-personal__button"><a class="popup-link" href="#popup-form-pass">Изменить</a></div>
                  </div>
                  <div class="content-personal__peculiarities peculiarities-personal">
                     <h3 class="peculiarities-personal__title">Особенности питания</h3>
                     <div class="select" id="food">
                        <button type="button" class="select__toggle icon-arrow-down icon" name="food" value=""
                           data-select="toggle" data-index="-1">Выберите</button>
                        <div class="select__dropdown">
                           <ul class="select__options">
                              <li class="select__option" data-select="option" data-value="food-0" data-index="0">
                                 Веган</li>
                              <li class="select__option" data-select="option" data-value="food-1" data-index="1">
                                 Мусульманин</li>
                              <li class="select__option" data-select="option" data-value="food-2" data-index="2">
                                 Ещё что-то</li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <h3 class="peculiarities-personal__title">Мои адреса</h3>
                  <div class="content-personal__info info-personal address">
                     <div class="info-personal__content">г. Москва, ул. Арбат, дом 1, кв. 15</div>
                     <div class="info-personal__button"><a class="popup-link remove-popup"
                           href="#popup-form-change">Изменить</a><button
                           class="control-item__remove remove-button">Удалить</button></div>
                     <div class="info-personal__content">г. Москва, ул. Арбат, дом 2, кв. 228</div>
                     <div class="info-personal__button"><a class="popup-link remove-popup"
                           href="#popup-form-change">Изменить</a><button
                           class="control-item__remove remove-button">Удалить</button></div>
                  </div>
                  <a href="#popup-form-add" class="info-personal__add icon-more popup-link">Добавить адрес</a>
               </div>
               <div class="personal__exit">
                  <a asp-area="" asp-controller="EcoHouse" asp-action="Index" class="exit icon-exit"><span>Выйти</span></a>
               </div>
            </div>
            <div id="popup-form-image" class="popup">
               <div class="popup__body">
                  <div class="popup__content content-popup">
                     <a href="#" class="popup__close close-popup icon-close"></a>
                     <h2 class="content-form-popup__title">Изменение фотографии</h2>
                     <div class="content-popup__form">
                        <form class="form personal download">
                           <div class="personal__image"></div>
                           <div class="input__wrapper">
                              <input name="file" type="file" name="file" id="input__file" class="input input__file"
                                 accept="image/*">
                              <label for="input__file" class="input__file-button">
                                 <span class="input__file-button-text">Загрузить</span>
                              </label>
                           </div>
                           <input class="input" type="submit" value="Сохранить" name="submit">
                        </form>
                     </div>
                  </div>
               </div>
            </div>
            <div id="popup-form-email" class="popup">
               <div class="popup__body">
                  <div class="popup__content content-popup">
                     <a href="#" class="popup__close close-popup icon-close"></a>
                     <h2 class="content-form-popup__title">Новая почта</h2>
                     <div class="content-popup__form">
                        <form class="form personal">
                           <input class="email place-form" type="text" name="email" placeholder="Email">
                           <input class="input" type="submit" value="Сохранить" name="submit">
                        </form>
                     </div>
                  </div>
               </div>
            </div>
            <div id="popup-form-phone" class="popup">
               <div class="popup__body">
                  <div class="popup__content content-popup">
                     <a href="#" class="popup__close close-popup icon-close"></a>
                     <h2 class="content-form-popup__title">Новый телефон</h2>
                     <div class="content-popup__form">
                        <form class="form personal">
                           <input class="number place-form" type="text" name="number" placeholder="+7 (">
                           <input class="input" type="submit" value="Сохранить" name="submit">
                        </form>
                     </div>
                  </div>
               </div>
            </div>
            <div id="popup-form-pass" class="popup">
               <div class="popup__body">
                  <div class="popup__content content-popup">
                     <a href="#" class="popup__close close-popup icon-close"></a>
                     <h2 class="content-form-popup__title">Старый пароль</h2>
                     <div class="content-popup__form">
                        <form class="form personal">
                           <div class="email__block form-block">
                              <input class="pass place-form" type="text" name="pass" placeholder="Пароль">
                              <div class="form__pass">Неверный пароль</div>
                           </div>
                           <div class="email__block form-block">
                              <h2 class="content-form-popup__title">Новый пароль</h2>
                              <input class="pass place-form" type="text" name="pass" placeholder="Пароль">
                           </div>
                           <input class="input" type="submit" value="Сохранить" name="submit">
                        </form>
                     </div>
                  </div>
               </div>
            </div>
            <div id="popup-form-add" class="popup">
               <div class="popup__body">
                  <div class="popup__content content-popup">
                     <a href="#" class="popup__close close-popup icon-close"></a>
                     <h2 class="content-form-popup__title">Добавление адреса</h2>
                     <div class="content-popup__form">
                        <form class="form personal address add">
                           <div class="city__block form-block">
                              <h6 class="form-block__title">Город</h6>
                              <input class="city place-form form-address" type="text" name="city" placeholder="Город">
                           </div>
                           <div class="address__block form-block">
                              <h6 class="form-block__title">Улица</h6>
                              <input class="address place-form form-address" type="text" name="address"
                                 placeholder="Улица">
                           </div>
                           <div class="EcoHouse__block form-block">
                              <h6 class="form-block__title">Дом</h6>
                              <input class="EcoHouse place-form form-address" type="text" name="EcoHouse" placeholder="Дом">
                           </div>
                           <div class="flat__block form-block">
                              <h6 class="form-block__title">Квартира/Офис</h6>
                              <input class="flat place-form form-address" type="text" name="flat"
                                 placeholder="Квартира/Офис">
                           </div>
                           <input class="input" type="submit" value="Сохранить" name="submit">
                        </form>
                     </div>
                  </div>
               </div>
            </div>
            <div id="popup-form-change" class="popup">
               <div class="popup__body">
                  <div class="popup__content content-popup">
                     <a href="#" class="popup__close close-popup icon-close"></a>
                     <h2 class="content-form-popup__title">Изменение адреса</h2>
                     <div class="content-popup__form">
                        <form class="form personal address change">
                           <div class="city__block form-block">
                              <h6 class="form-block__title">Город</h6>
                              <input class="city place-form form-address" type="text" name="city" placeholder="Город">
                           </div>
                           <div class="address__block form-block">
                              <h6 class="form-block__title">Улица</h6>
                              <input class="address place-form form-address" type="text" name="address"
                                 placeholder="Улица">
                           </div>
                           <div class="EcoHouse__block form-block">
                              <h6 class="form-block__title">Дом</h6>
                              <input class="EcoHouse place-form form-address" type="text" name="EcoHouse" placeholder="Дом">
                           </div>
                           <div class="flat__block form-block">
                              <h6 class="form-block__title">Квартира/Офис</h6>
                              <input class="flat place-form form-address" type="text" name="flat"
                                 placeholder="Квартира/Офис">
                           </div>
                           <input class="input" type="submit" value="Сохранить" name="submit">
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </section>